### ISSUE TITLE
"Darc" is spelled "Dark" in current theme selction

### ISSUE THREAD

**Issue by InfiniteLoopGameDev** [lucasstarsz/Compose#1]
## Platform Info
- [x] Windows (Version: Windows 10 20H2)

**Describe the bug**
Darc is Dark not Darc

## Expected behavior
It showing Darc

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to 'File'
2. Click on 'Settings'
3. See error

## Media Aid
![image](https://user-images.githubusercontent.com/44796943/109556295-8a797780-7ace-11eb-9e80-e8fa5c19adc3.png)

YAY! First bug report

**Comment by lucasstarsz** [comment]
Congrats on opening your first issue! 🎉
I'll make sure to fix that little bug and have it ready for 0.2.1. Thanks, and don't be afraid to open more issues if you find them!

**Comment by lucasstarsz** [comment]
This bug has been fixed in the v0.2.1 branch. Thank you for reporting this issue!
