### ISSUE TITLE
Pressing enter fails with one tab on the first line

### ISSUE THREAD

**Issue by rushilkoul** [lucasstarsz/Compose#15]
## Platform Info
- [x] Linux
  - Version: all
- [x] Windows
  - Version: all
- [x] Mac OS
  - Version: all

**Describe the bug**

On entering the first line, and pressing `tab` and typing something, works as expected. but I cannot switch to the next line after pressing tab(no matter how many times). 

## Expected behavior
It should have switched to the next line

**To Reproduce**
_Steps to reproduce the behavior:_
1. Open Compose.
2. On the first line, press tab.
3. Type something if you want to(doesn't matter in this case)
4. Press enter.
5. It doesn't switch to the next line.

## Media Aid
_If applicable, add screenshots/GIFs/Videos to help explain your problem._
![Screen Shot 2021-03-03 at 11 02 07 AM](https://user-images.githubusercontent.com/64902289/109757501-e697e500-7c0f-11eb-8db3-9d181e471388.png)

**Comment by lucasstarsz** [comment]
After some testing, I've concluded this error occurs on all platforms as it is not related to the platform. I'll change the issue content for future reference.

**Comment by lucasstarsz** [comment]
At first glance, it seems to be an issue with how the leading tab count is counted.
I'll make sure to fix it for v0.2.2. Thanks for sharing!

**Comment by rushilkoul** [comment]
but have you seen tab??!!!?!!???
