### ISSUE TITLE
[FEATURE REQUEST] Text Wrap should be on by default

### ISSUE THREAD

**Issue by mellobacon** [lucasstarsz/Compose#3]
Self explanatory. I think text wrap should be on by default because if you make the window smaller is more convenient if you have a lot of text.

## What should the solution be like?
For text wrap to be checked in settings when you open the window.

**Comment by lucasstarsz** [comment]
That's a fair consideration -- I'll make that change right away.
Honestly, I don't see why it should be disabled by default either!

**Comment by lucasstarsz** [comment]
This feature has been added in the v0.2.1 branch.
